name: Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: |
          docker build \
            -t jstgrwup/devtinder:latest \
            --build-arg NEXT_PUBLIC_NODE_ENV=production \
            --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
            .

      - name: Publish image to docker hub
        run: docker push jstgrwup/devtinder:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Stop old container
        run: docker stop devtiner-app-container || true

      - name: Remove old container
        run: docker rm devtiner-app-container || true

      - name: Remove unused images and volumes
        run: docker system prune -a -f --volumes

      - name: Pull image from docker hub
        run: docker pull jstgrwup/devtinder:latest

      - name: Delete old container
        run: docker rm -f devtiner-app-container || true

      - name: Run docker container
        run: docker run -d -p 3000:3000 --name devtiner-app-container jstgrwup/devtinder:latest
